### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by sandeshlasnapure** [julianfalcionelli/MagicForm#1]
Not showing error messages.

**Comment by julianfalcionelli** [comment]
Hi @sandeshlasnapure , you need to set your message in each validation. For example using the NotEmptyValidation: `.addValidation(new ValidationNotEmpty().setMessage("Hola"))`

**Comment by sandeshlasnapure** [comment]
MagicForm mMagicForm = new MagicForm(ValidationMode.ON_CONTENT_CHANGE)
                // Mobile validator
                .addField(new FormField(enterMobileNumber)
                        .addValidation(new ValidationMinLength(10).setMessage("Enter 10 digit mobile number")))
                // FirstName validator
                .addField(new FormField(enter_first_name)
                        .addValidation(new ValidationNotEmpty().setMessage("Required Field"))
                        .addValidation(new ValidationRegex(RegexPattern(nameRegex)).setMessage("Enter Human name")))
                // LastName validator
                .addField(new FormField(enter_last_name)
                        .addValidation(new ValidationNotEmpty().setMessage("Required Field"))
                        .addValidation(new ValidationRegex(RegexPattern(nameRegex)).setMessage("Enter Human name")))
                // Password
                .addField(new FormField(enterPassword)
                        .addValidation(new ValidationNotEmpty().setMessage("Required Field"))
                        .addValidation(new ValidationLength(4, 10).setMessage("Password must contain at least 4 character")))

I am doing the same thing still no luck.

**Comment by sandeshlasnapure** [comment]
![20160426_185441](https://cloud.githubusercontent.com/assets/12455411/14819177/78760fda-0bde-11e6-8a27-3da7a553de56.png)

**Comment by julianfalcionelli** [comment]
Thats weird, it seems to be a problem with styles. I just test your form with own views and worked well.

**Comment by julianfalcionelli** [comment]
![screenshot_2016-04-26-10-17-05](https://cloud.githubusercontent.com/assets/5782994/14819350/29f93350-0b98-11e6-99eb-ae15b567016a.png)

**Comment by sandeshlasnapure** [comment]
Am using AppCompatEditText with Theme.AppCompat.DayNight.NoActionBar
<com.sandesh.voci.wedget.MaterialEditText
                            android:id="@+id/enterMobileNumber"
                            android:layout_width="match_parent"
                            android:layout_height="40dp"
                            android:hint="@string/enter_mobile_number"
                            android:inputType="number"
                            android:maxLength="10"
                            android:singleLine="true"
                            android:textColor="@color/et_text_color_registration"
                            android:textSize="@dimen/edit_text_size"
                            android:theme="@style/EditText.Style" />

**Comment by julianfalcionelli** [comment]
I just try with AppCompatEditText and it worked well, what are you setting in the style/EditText.Style ?

**Comment by sandeshlasnapure** [comment]
<style name="EditText.Style" parent="android:Widget.EditText">
        <item name="android:textColor">#000</item>
        <item name="android:textColorHint">@color/et_text_hint_color_registration</item>
        <item name="colorControlActivated">@color/colorPrimaryDark</item>
        <item name="android:textSize">@dimen/edit_text_size</item>
        <item name="colorAccent">@color/md_blue_grey_500</item>
    </style>

**Comment by sandeshlasnapure** [comment]
Its working with AppCompatEditText as expected but I need to switch between day and night mode so thats why I need to use themes for edittext.

**Comment by julianfalcionelli** [comment]
That issue is happening in both modes ? (day and night)

**Comment by sandeshlasnapure** [comment]
Yes.

**Comment by julianfalcionelli** [comment]
@sandeshlasnapure try setting the following value in your EditText.Style:

```
   ` <item name="android:textColorPrimaryInverse">#FFF</item>`
```

**Comment by sandeshlasnapure** [comment]
Stil not working.

**Comment by julianfalcionelli** [comment]
are you using `android:theme="@style/EditText.Style"` instead of  `style="..."`, is that correct ?

**Comment by julianfalcionelli** [comment]
I can´t reproduce the error, let me know any news . The same should be a matter of styles which would be independent of this library.

**Comment by sandeshlasnapure** [comment]
Yes, to change the color control normal and activate I had to use theme which can not be done by using style.
