### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by tamsir** [julianfalcionelli/MagicForm#4]
It will be better if you add jumper conditions.
Thanks

**Comment by julianfalcionelli** [comment]
Hi @tamsir , I am glad that you like the library :) .

Could you explain what you mean with jumper conditions (conditions at the form intialization ?) and for what you would need it, just to evaluate if is a good feature that could be included.

Thanks.

**Comment by tamsir** [comment]
Hello Julian
Thanks to your reply
It mean when your make a form survey per example to have possibility to see
or hide a question based to previous answer.
Thanks.

Le 20 avr. 2017 01:48, "Julian Falcionelli" <notifications@github.com> a
écrit :
