### ISSUE TITLE
[Bug?] Validation mode ON_FOCUS, if field already has a value, callback will be onFailure()

### ISSUE THREAD

**Issue by rrreche** [julianfalcionelli/MagicForm#5]
I am having troubles validating forms with mode ON_FOCUS. The situation is as follows:

- I have two text fields, both with preset values and non-empty validation
- If I modify one of them, failure callback will trigger, despite having text in both fields.
- When I modify the second one, then onSuccess will be triggered.

If I am not mistaken, the problem could lie in checkFormStatus(), which checks mFields.size() == mValidFields.size(). The solution would be checking the field value in the very moment it is added (addField method) to increase mValidFields. Right now, mValidFieldsSize only increases when the field is modified.

I would do this myself, but I have little knowledge when it comes to forking and requesting pulls in git, my apologies!

**Comment by julianfalcionelli** [comment]
Hi @rrreche, I will take a look on that!

**Comment by julianfalcionelli** [comment]
@rrreche already fixed in version 1.4 !

Please replace your dependency for:     

`compile 'julianfalcionelli:MagicForm:1.4'`

Thanks for your feedback.

**Comment by rrreche** [comment]
Cool! An early fix. I already worked it around using ON_VALIDATE in my app, but since I will be using this library for more forms, I will come back and report if the issue has been solved in a day or two (I hope) from here.

Thank you for your work, nice lib! :-)
