### ISSUE TITLE
need a torch

### ISSUE THREAD

**Issue by Marcosmaliki** [julianfalcionelli/MagicForm#9]
I'm in darkness. How do we link this with the activity layout. Where is the styling?

**Comment by julianfalcionelli** [comment]
Hi @Marcosmaliki , this library is style-agnostic (independent of the XML styling), is just for validations. You just need the View reference that was already inflated in your Activity / Fragment to includ it into the MagicForm object.

For example you can have this in your Styles.xml:

```
<style name="FormErrorStyle" parent="@android:style/TextAppearance">
    <item name="android:textColor">@color/redFormError</item>
    <item name="android:textSize">12sp</item>
</style>
```

And then use it in your Activity / Fragment Layuot:

```
<android.support.design.widget.TextInputLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:errorTextAppearance="@style/FormErrorStyle">
        <EditText ..../>
</android.support.design.widget.TextInputLayout>
```
